name: RenewableDragonEggs
main: io.github.rypofalem.renewabledragoneggs.RenewableDragonEggPlugin
version: 3
api-version: 1.13
website: rypofalem.github.io
author: RypoFalem
description: When the enddragon dies, place a dragon egg on the highest bedrock at 0,0